### ISSUE TITLE
Error during on enable

### ISSUE THREAD

**Issue by wsj7178** [pldrjs/pldr.js#1]
11:41:09 [ERROR] [pldr.js] Error while exporting resources
java.nio.file.NoSuchFileException: scripts\node_modules\babel-polyfill.npmignore
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.nio.file.Files.newOutputStream(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at org.pldrjs.pldrjs.PldrJS.onEnable(PldrJS.java:138)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:456)
        at cn.nukkit.Server.enablePlugin(Server.java:618)
        at cn.nukkit.Server.enablePlugins(Server.java:607)
        at cn.nukkit.Server.<init>(Server.java:454)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by HelloWorld017** [comment]
Fixed on PldrJS 1.1.0
